"""Add percent column

Revision ID: 82f858c4ac71
Revises: 38a7a0a907e3
Create Date: 2025-05-23 19:26:54.801432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f858c4ac71'
down_revision = '38a7a0a907e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percent', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_price', schema=None) as batch_op:
        batch_op.drop_column('percent')

    # ### end Alembic commands ###
